FROM debian

RUN apt-get update
RUN apt-get install -y git
RUN git clone https://github.com/rafutek/music-dl.git

RUN apt-get install -y make g++
RUN apt-get install -y libboost-all-dev libtag1-dev

RUN cd music-dl/src/ && make && ./music-dl -h